### ISSUE TITLE
Continuation run fails when using k-points

### ISSUE THREAD

**Issue by artuuuro** [LLNL/qball#17]
When I try to continue a simulation that has more than 1 k-point, the program exits with a segfault just after having loaded the save states or hangs and does nothing (running on BlueGene). 

################## First run (this works fine): ##############
set cell 10.0 0.0 0.0 0.0 10.0 0.0 0.0 0.0 10.0

species Ni Ni_HSCV_LDA-1.0.xml
species Cr Cr_HSCV_LDA-1.0.xml

atom Ni0 Ni 0.0 0.0 0.0
atom Cr1 Cr 0.0 3.5 3.5

set ecut 50 Ry                                                                                                                   
set nempty 32

set nkpoints 4
set nparallelkpts 1

kpoint 0.00 0.00 0.00 1.000 crystal
kpoint 0.50 0.00 0.00 1.000 crystal
kpoint 0.00 0.50 0.00 1.000 crystal
kpoint 0.00 0.00 0.50 1.000 crystal

run 0 10 10
status

save -dump wf/states
savesys wf/sys

################## Second run (segfaults or hangs): ##############
wf/sys
set ecut 50 Ry
set nempty 32

set nkpoints 4
set nparallelkpts 1

kpoint 0.00 0.00 0.00 1.000 crystal
kpoint 0.50 0.00 0.00 1.000 crystal
kpoint 0.00 0.50 0.00 1.000 crystal
kpoint 0.00 0.00 0.50 1.000 crystal

load -dump wf/states

run 0 10 10

save -dump wf/states
savesys wf/sys

############################################################
The program hangs/segfaults usually at following output lines

ChargeDensity:  vbasis = 48 48 48, resize to 56 56 56

**Comment by draeger1** [comment]
How many MPI tasks are you running with?  What happens if you try save -states and load -states instead?

Also, note that the last argument in your run command should probably be 2-5, those are typically the most efficient values.

**Comment by artuuuro** [comment]
I have tried 16(nodes)x8 configuration as well as 2x8. Both behave the same way. Also, initial run and continuation have the same node/core configuration.

I have tried using the -states option with the same outcomes yesterday. Today it seems to work. Maybe they are still having issues with the cluster.

**Comment by artuuuro** [comment]
So it seems that this issue is still occurring if I use dump option instead of states.

**Comment by draeger1** [comment]
Hardware or system problems could be responsible, we've seen similar issues at LLNL from time to time.  The -dump option is one file per task, which is probably the most stressful on the I/O system.  The -states option is only marginally slower and a lot more flexible, as you can restart with different numbers of tasks or process grid dimensions, and it should tax the I/O nodes on a BG/Q machine a lot less.  I would try using -states from now on and seeing if the issue regularly recurs.
