### ISSUE TITLE
Large difference between etotal_int and etotal values

### ISSUE THREAD

**Issue by artuuuro** [LLNL/qball#25]
Hi,

I do not know if this is a real issue or I am doing something wrong, but Alfredo told me to write here.

If I try to find converge the ground state of a system with qball (also with the latest version on bg/q) I see a large difference (about 700 H) between etotal and etotal_int values in some cases. I have attached  the input files I use to run the calculation.

The problem arises when I use:
run 0 1000 10 (for example)
and I do not see this behaviour if I use:
run 0 1000

Result is like this:
[plot.pdf](https://github.com/LLNL/qball/files/1325821/plot.pdf)

Best wishes,
Artur

[find_gs.qbi]
set force_complex_wf ON
set stress ON
set nrowmax 256

struc.qbs

set ecut 150 Ry
randomize_wf

set wf_dyn PSDA

run 0 500
run 0 100 5
run 0 100 5
run 0 500
run 0 500
run 0 100 5
run 0 100 5

[struc.qbs]
set cell 20.465734 0.000000 0.000000 0.000000 20.465734 0.000000 0.000000 0.000000 20.465734
species Cu Cu_HSCV_LDA-1.0.xml
atom Cu0 Cu 0.000000 0.000000 0.000000
atom Cu1 Cu 3.410962 3.410962 0.000000
... (FCC structure with 108 atoms)

[sbatch job]
The things that go in front for 128 node run on vulcan

echo "### Start"
date
srun ~/Bin/qball_vulcan find_gs.qbi > find_gs.out
grep etotal_int find_gs.out > Energy.data
grep '<etotal>' find_gs.out > Etotal.data
echo "### Finish"
date

**Comment by artuuuro** [comment]
Here are selected parts from the output

```
$ grep -e etotal -e "\[qball\] run" find_gs.out | grep '<etotal>' -A2 -B2

<etotal_int scf_iter="498"> -15355.88596670 </etotal_int>
<etotal_int scf_iter="499"> -15355.88672732 </etotal_int>
<etotal> -15355.88748327 </etotal>
<!-- [qball] run 0 100 5 -->
<etotal_int scf_iter="0"> -15355.88748327 </etotal_int>
--
<etotal_int scf_iter="99"> -16120.63551212 </etotal_int>
<etotal_int scf_iter="99"> -16120.63558612 </etotal_int>
<etotal> -15347.70609726 </etotal>
<!-- [qball] run 0 100 5 -->
<etotal_int scf_iter="0"> -15347.70609726 </etotal_int>
--
  <etotal_int scf_iter="99"> -16120.63021495 </etotal_int>
  <etotal_int scf_iter="99"> -16120.63015599 </etotal_int>
  <etotal> -15347.70645495 </etotal>
<!-- [qball] run 0 500 -->
  <etotal_int scf_iter="0"> -15347.70645495 </etotal_int>
--
  <etotal_int scf_iter="498"> -15355.97930157 </etotal_int>
  <etotal_int scf_iter="499"> -15355.97930928 </etotal_int>
  <etotal> -15355.97931714 </etotal>
<!-- [qball] run 0 500 -->
  <etotal_int scf_iter="0"> -15355.97931714 </etotal_int>
--
  <etotal_int scf_iter="498"> -15355.98065960 </etotal_int>
  <etotal_int scf_iter="499"> -15355.98066082 </etotal_int>
  <etotal> -15355.98066150 </etotal>
<!-- [qball] run 0 100 5 -->
  <etotal_int scf_iter="0"> -15355.98066150 </etotal_int>
--
  <etotal_int scf_iter="99"> -16120.64456473 </etotal_int>
  <etotal_int scf_iter="99"> -16120.64466469 </etotal_int>
  <etotal> -15347.71652780 </etotal>
<!-- [qball] run 0 100 5 -->
  <etotal_int scf_iter="0"> -15347.71652780 </etotal_int>
--
  <etotal_int scf_iter="99"> -16120.63356596 </etotal_int>
  <etotal_int scf_iter="99"> -16120.63358043 </etotal_int>
  <etotal> -15347.71388509 </etotal>
```

**Comment by draeger1** [comment]
Hi Artur,

If you don't have empty states, you don't want to enable non-scf iterations (the last argument to the run command).  It turns on charge mixing by default (which I believe is the difference you're seeing between etotal_int and etotal) and can create convergence problems for some systems.  

However, if this is bulk copper, you're going to want empty states and possibly k-points to get a well-converged result.  Alfredo or Xavier should be able to supply you with an example input file for this case.

Best,
  Erik

**Comment by artuuuro** [comment]
Hi,

So what you are saying is that the issue is related to the system being a metal. If I would add additional states etotal and etotal_int would converge to the same/similar value.

If I need to run TDDFT is it possible to use wf_dyn FORKTD with empty states?

Artur
