### ISSUE TITLE
continuation of a simulation

### ISSUE THREAD

**Issue by gmassillon** [LLNL/qball#41]
Hello,
 I run a simulation for the ground state which is not converged, is there a possibility to continue the simulation using a restart command?

**Comment by gmassillon** [comment]
Hello,
I run a simulation for the ground state which is not converged, is there a possibility to continue the simulation using a restart command?

**Comment by correaa** [comment]
There is no restart command as far I know. 
You save your unconverged wavefunctions once in a while and load it later to continue.
