### ISSUE TITLE
Units in Qball

### ISSUE THREAD

**Issue by gmassillon** [LLNL/qball#42]
What are the units for the following parameters in Qball?

Force is in N?
Energy in Rydberg or a.u.?
Stopping power in eV/A?

**Comment by correaa** [comment]
It is all atomic units (bohr, Hartree, and forces Hartree over bohr), except perhaps when eigenvalues are printed.
There is no output of "stopping power" of course but if calculated from other quantities it will come out in the same units as a force (atomic units = Hartree over bohr).
